pub const Decode = error{
    ChunkIsNotHeader,
    InvalidBitsPerPixel,
    InvalidChunkType,
    InvalidCompression,
    InvalidDataLength,
    InvalidEndMarker,
    InvalidFormat,
    InvalidHeader,
    InvalidHeaderLength,
    InvalidHeaderSize,
    InvalidDimensions,
    InvalidImportantColors,
    InvalidNumberOfColors,
    InvalidRLEData,
    InvalidTGAEnum,
    DataOutOfBounds,
    UnsupportedBitsPerPixel,
    UnsupportedCompression,
    UnsupportedType,
    UnsupportedDepth,
    UnexpectedEndOfData,
    UnsupportedNumberOfChannels,
    UnexpectedSignature,
    UnsupportedSuperCompression,
};

pub const Encode = error{
    InvalidDimensions,
    UnsupportedChannel,
    UnsupportedColorspace,
};
